server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/GBValdez/springMicroservice.git
          search-paths: Config-Data
  application:
    name: Config-Service
